// Generated by gencpp from file seer/SeerGoal.msg
// DO NOT EDIT!


#ifndef SEER_MESSAGE_SEERGOAL_H
#define SEER_MESSAGE_SEERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seer
{
template <class ContainerAllocator>
struct SeerGoal_
{
  typedef SeerGoal_<ContainerAllocator> Type;

  SeerGoal_()
    : cmd(0)  {
    }
  SeerGoal_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::seer::SeerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seer::SeerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SeerGoal_

typedef ::seer::SeerGoal_<std::allocator<void> > SeerGoal;

typedef boost::shared_ptr< ::seer::SeerGoal > SeerGoalPtr;
typedef boost::shared_ptr< ::seer::SeerGoal const> SeerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seer::SeerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seer::SeerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seer': ['/home/zwa/my_ws_actual/devel/share/seer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seer::SeerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seer::SeerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seer::SeerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seer::SeerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seer::SeerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seer::SeerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seer::SeerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66990e73c7aab0c47ddcdc70f7fa5bd0";
  }

  static const char* value(const ::seer::SeerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66990e73c7aab0c4ULL;
  static const uint64_t static_value2 = 0x7ddcdc70f7fa5bd0ULL;
};

template<class ContainerAllocator>
struct DataType< ::seer::SeerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seer/SeerGoal";
  }

  static const char* value(const ::seer::SeerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seer::SeerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Send a flag to server to control the thread start, pause, restart and stop\n\
#command == 1 start\n\
#command == 0 stop\n\
int32 cmd\n\
";
  }

  static const char* value(const ::seer::SeerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seer::SeerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seer::SeerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seer::SeerGoal_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEER_MESSAGE_SEERGOAL_H
