// Generated by gencpp from file mag_track/MagTrackFeedback.msg
// DO NOT EDIT!


#ifndef MAG_TRACK_MESSAGE_MAGTRACKFEEDBACK_H
#define MAG_TRACK_MESSAGE_MAGTRACKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace mag_track
{
template <class ContainerAllocator>
struct MagTrackFeedback_
{
  typedef MagTrackFeedback_<ContainerAllocator> Type;

  MagTrackFeedback_()
    : detected(false)
    , box_pos()
    , box_ori()  {
    }
  MagTrackFeedback_(const ContainerAllocator& _alloc)
    : detected(false)
    , box_pos(_alloc)
    , box_ori(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _box_pos_type;
  _box_pos_type box_pos;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _box_ori_type;
  _box_ori_type box_ori;





  typedef boost::shared_ptr< ::mag_track::MagTrackFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mag_track::MagTrackFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MagTrackFeedback_

typedef ::mag_track::MagTrackFeedback_<std::allocator<void> > MagTrackFeedback;

typedef boost::shared_ptr< ::mag_track::MagTrackFeedback > MagTrackFeedbackPtr;
typedef boost::shared_ptr< ::mag_track::MagTrackFeedback const> MagTrackFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mag_track::MagTrackFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mag_track::MagTrackFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mag_track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mag_track': ['/home/zwa/my_ws/devel/share/mag_track/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mag_track::MagTrackFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mag_track::MagTrackFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mag_track::MagTrackFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8531b17567cd8e707400025bcf07e9b8";
  }

  static const char* value(const ::mag_track::MagTrackFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8531b17567cd8e70ULL;
  static const uint64_t static_value2 = 0x7400025bcf07e9b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mag_track/MagTrackFeedback";
  }

  static const char* value(const ::mag_track::MagTrackFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
bool detected\n\
geometry_msgs/Vector3 box_pos\n\
geometry_msgs/Vector3 box_ori\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mag_track::MagTrackFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected);
      stream.next(m.box_pos);
      stream.next(m.box_ori);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagTrackFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mag_track::MagTrackFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mag_track::MagTrackFeedback_<ContainerAllocator>& v)
  {
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "box_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.box_pos);
    s << indent << "box_ori: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.box_ori);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAG_TRACK_MESSAGE_MAGTRACKFEEDBACK_H
