// Generated by gencpp from file mag_track/MagTrackResult.msg
// DO NOT EDIT!


#ifndef MAG_TRACK_MESSAGE_MAGTRACKRESULT_H
#define MAG_TRACK_MESSAGE_MAGTRACKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mag_track
{
template <class ContainerAllocator>
struct MagTrackResult_
{
  typedef MagTrackResult_<ContainerAllocator> Type;

  MagTrackResult_()
    : result(0.0)  {
    }
  MagTrackResult_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::mag_track::MagTrackResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mag_track::MagTrackResult_<ContainerAllocator> const> ConstPtr;

}; // struct MagTrackResult_

typedef ::mag_track::MagTrackResult_<std::allocator<void> > MagTrackResult;

typedef boost::shared_ptr< ::mag_track::MagTrackResult > MagTrackResultPtr;
typedef boost::shared_ptr< ::mag_track::MagTrackResult const> MagTrackResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mag_track::MagTrackResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mag_track::MagTrackResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mag_track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mag_track': ['/home/zwa/my_ws/devel/share/mag_track/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mag_track::MagTrackResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mag_track::MagTrackResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mag_track::MagTrackResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mag_track::MagTrackResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mag_track::MagTrackResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mag_track::MagTrackResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mag_track::MagTrackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::mag_track::MagTrackResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::mag_track::MagTrackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mag_track/MagTrackResult";
  }

  static const char* value(const ::mag_track::MagTrackResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mag_track::MagTrackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float32 result\n\
";
  }

  static const char* value(const ::mag_track::MagTrackResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mag_track::MagTrackResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagTrackResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mag_track::MagTrackResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mag_track::MagTrackResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAG_TRACK_MESSAGE_MAGTRACKRESULT_H
