#Send a flag to server to control the thread start, pause, restart and stop
#command == 1 start
#command == 2 pause
#command == 3 stop
int32 command
---
float32 result
---
#feedback
bool detected
geometry_msgs/Vector3 box_pos
geometry_msgs/Vector3 box_ori
