// Generated by gencpp from file obstacle_scan/ObstacleScanFeedback.msg
// DO NOT EDIT!


#ifndef OBSTACLE_SCAN_MESSAGE_OBSTACLESCANFEEDBACK_H
#define OBSTACLE_SCAN_MESSAGE_OBSTACLESCANFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_scan
{
template <class ContainerAllocator>
struct ObstacleScanFeedback_
{
  typedef ObstacleScanFeedback_<ContainerAllocator> Type;

  ObstacleScanFeedback_()
    : found_obst()
    , obst_status()  {
    }
  ObstacleScanFeedback_(const ContainerAllocator& _alloc)
    : found_obst(_alloc)
    , obst_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _found_obst_type;
  _found_obst_type found_obst;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _obst_status_type;
  _obst_status_type obst_status;





  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleScanFeedback_

typedef ::obstacle_scan::ObstacleScanFeedback_<std::allocator<void> > ObstacleScanFeedback;

typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanFeedback > ObstacleScanFeedbackPtr;
typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanFeedback const> ObstacleScanFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obstacle_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'obstacle_scan': ['/home/zwa/my_ws_actuell/devel/share/obstacle_scan/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe07c0f77aefdf2c6909714df7a946d";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe07c0f77aefdf2ULL;
  static const uint64_t static_value2 = 0xc6909714df7a946dULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_scan/ObstacleScanFeedback";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32[] found_obst\n\
int32[] obst_status\n\
\n\
";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found_obst);
      stream.next(m.obst_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleScanFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_scan::ObstacleScanFeedback_<ContainerAllocator>& v)
  {
    s << indent << "found_obst[]" << std::endl;
    for (size_t i = 0; i < v.found_obst.size(); ++i)
    {
      s << indent << "  found_obst[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.found_obst[i]);
    }
    s << indent << "obst_status[]" << std::endl;
    for (size_t i = 0; i < v.obst_status.size(); ++i)
    {
      s << indent << "  obst_status[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.obst_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_SCAN_MESSAGE_OBSTACLESCANFEEDBACK_H
