// Generated by gencpp from file obstacle_scan/ObstacleScanResult.msg
// DO NOT EDIT!


#ifndef OBSTACLE_SCAN_MESSAGE_OBSTACLESCANRESULT_H
#define OBSTACLE_SCAN_MESSAGE_OBSTACLESCANRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_scan
{
template <class ContainerAllocator>
struct ObstacleScanResult_
{
  typedef ObstacleScanResult_<ContainerAllocator> Type;

  ObstacleScanResult_()
    : finished(false)  {
    }
  ObstacleScanResult_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleScanResult_

typedef ::obstacle_scan::ObstacleScanResult_<std::allocator<void> > ObstacleScanResult;

typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanResult > ObstacleScanResultPtr;
typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanResult const> ObstacleScanResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obstacle_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'obstacle_scan': ['/home/zwa/my_ws_actuell/devel/share/obstacle_scan/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_scan/ObstacleScanResult";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool finished\n\
";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleScanResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_scan::ObstacleScanResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_scan::ObstacleScanResult_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_SCAN_MESSAGE_OBSTACLESCANRESULT_H
