// Generated by gencpp from file obstacle_scan/ObstacleScanGoal.msg
// DO NOT EDIT!


#ifndef OBSTACLE_SCAN_MESSAGE_OBSTACLESCANGOAL_H
#define OBSTACLE_SCAN_MESSAGE_OBSTACLESCANGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_scan
{
template <class ContainerAllocator>
struct ObstacleScanGoal_
{
  typedef ObstacleScanGoal_<ContainerAllocator> Type;

  ObstacleScanGoal_()
    : checkpoint(0)  {
    }
  ObstacleScanGoal_(const ContainerAllocator& _alloc)
    : checkpoint(0)  {
  (void)_alloc;
    }



   typedef int32_t _checkpoint_type;
  _checkpoint_type checkpoint;





  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleScanGoal_

typedef ::obstacle_scan::ObstacleScanGoal_<std::allocator<void> > ObstacleScanGoal;

typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanGoal > ObstacleScanGoalPtr;
typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanGoal const> ObstacleScanGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obstacle_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'obstacle_scan': ['/home/zwa/my_ws_actuell/devel/share/obstacle_scan/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa4d80319421fdd4afb9a7340a190c1a";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa4d80319421fdd4ULL;
  static const uint64_t static_value2 = 0xafb9a7340a190c1aULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_scan/ObstacleScanGoal";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Send a flag to server to control the thread start, pause, restart and stop\n\
#checkPoint == 1 2 3 start\n\
#command == 0 stop\n\
int32 checkpoint\n\
";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checkpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleScanGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator>& v)
  {
    s << indent << "checkpoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.checkpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_SCAN_MESSAGE_OBSTACLESCANGOAL_H
