// Generated by gencpp from file obstacle_scan/ObstacleScanActionGoal.msg
// DO NOT EDIT!


#ifndef OBSTACLE_SCAN_MESSAGE_OBSTACLESCANACTIONGOAL_H
#define OBSTACLE_SCAN_MESSAGE_OBSTACLESCANACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <obstacle_scan/ObstacleScanGoal.h>

namespace obstacle_scan
{
template <class ContainerAllocator>
struct ObstacleScanActionGoal_
{
  typedef ObstacleScanActionGoal_<ContainerAllocator> Type;

  ObstacleScanActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ObstacleScanActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleScanActionGoal_

typedef ::obstacle_scan::ObstacleScanActionGoal_<std::allocator<void> > ObstacleScanActionGoal;

typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanActionGoal > ObstacleScanActionGoalPtr;
typedef boost::shared_ptr< ::obstacle_scan::ObstacleScanActionGoal const> ObstacleScanActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obstacle_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'obstacle_scan': ['/home/zwa/my_ws_actuell/devel/share/obstacle_scan/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae162dbda42ed2b64243d440ca561275";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae162dbda42ed2b6ULL;
  static const uint64_t static_value2 = 0x4243d440ca561275ULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_scan/ObstacleScanActionGoal";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
ObstacleScanGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: obstacle_scan/ObstacleScanGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Send a flag to server to control the thread start, pause, restart and stop\n\
#checkPoint == 1 2 3 start\n\
#command == 0 stop\n\
int32 checkpoint\n\
";
  }

  static const char* value(const ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleScanActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_scan::ObstacleScanActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::obstacle_scan::ObstacleScanGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_SCAN_MESSAGE_OBSTACLESCANACTIONGOAL_H
